import { StyleSheet } from 'react-native';

import { SCREEN_HEIGHT, SCREEN_WIDTH } from './constants';
import { shortVideoTheme } from './theme';

export const styles = StyleSheet.create({
  reelContainer: { flex: 1 },
  uiOverlay: { flex: 1, justifyContent: 'flex-end', paddingHorizontal: 16, zIndex: 20 },

  sideActionsColumn: {
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginBottom: 20,
    gap: 22,
    paddingRight: 4,
  },
  sideAction: { alignItems: 'center' },
  playPauseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  playIconNudge: { marginLeft: 1 },
  sideLabel: {
    color: '#fff',
    fontSize: 11,
    marginTop: 3,
    fontWeight: '600',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },

  textContent: { width: '100%' },
  titleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  reelTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    marginRight: 6,
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },

  epBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 10,
  },
  epBadgeText: {
    color: shortVideoTheme.crimson,
    fontSize: 12,
    fontWeight: '700',
  },

  tagsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tagPill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  tagText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  descText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
    paddingRight: 50,
  },
  synopsisContainer: {
    width: '100%',
  },
  moreLessButton: {
    alignSelf: 'flex-start',
    marginTop: 2,
    marginBottom: 10,
  },
  moreLessText: {
    color: shortVideoTheme.crimson,
    fontSize: 14,
    fontWeight: '700',
  },

  progressContainer: { marginBottom: 12 },
  progressBarHitArea: {
    paddingVertical: 12,
    marginVertical: -8,
    justifyContent: 'center',
  },
  progressBarTrack: {
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    position: 'relative',
  },
  progressBarTrackScrubbing: {
    height: 6,
    borderRadius: 3,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: shortVideoTheme.crimson,
    borderRadius: 2,
  },
  scrubberDot: {
    position: 'absolute',
    top: -5,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: shortVideoTheme.crimson,
    marginLeft: -6,
  },
  scrubberDotScrubbing: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginLeft: -8,
    top: -5,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  timeText: { color: 'rgba(255,255,255,0.7)', fontSize: 11, fontWeight: '500' },

  episodeStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  episodeText: { color: '#fff', fontSize: 14, fontWeight: '700', marginLeft: 8 },
  watchAllText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '600',
    marginRight: 4,
  },
  topSearch: { position: 'absolute', right: 20, padding: 10 },

  dramaVideoFrame: {
    position: 'absolute',
    left: 0,
    right: 0,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  youtubeVideoFrame: {
    position: 'absolute',
    left: 0,
    right: 0,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  youtubeFullscreenHint: {
    position: 'absolute',
    alignSelf: 'center',
    maxWidth: '88%',
    zIndex: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  youtubeFullscreenHintText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },

  pauseOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pauseIconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 4,
  },

  lockOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  lockIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,45,85,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,45,85,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  lockTitle: { color: '#fff', fontSize: 16, fontWeight: '600', marginBottom: 8 },
  lockBalance: { color: '#ccc', fontSize: 14, marginBottom: 12 },
  lockError: { color: '#ff6b6b', fontSize: 13, marginBottom: 10, textAlign: 'center', paddingHorizontal: 24 },
  lockButton: {
    backgroundColor: '#FF2D55',
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 160,
    alignItems: 'center',
  },
  lockButtonDisabled: { opacity: 0.5 },
  lockButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  lockSecondaryButton: { marginTop: 12, paddingVertical: 8 },
  lockSecondaryText: { color: '#FF2D55', fontSize: 14, fontWeight: '600' },

  bufferingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  errorOverlayText: {
    color: '#ff6b6b',
    fontSize: 14,
    textAlign: 'center',
  },
  speedChip: {
    position: 'absolute',
    left: 14,
    zIndex: 50,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  speedChipText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  speedModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
    paddingBottom: 32,
  },
  speedModalCard: {
    marginHorizontal: 16,
    backgroundColor: '#1c1c1e',
    borderRadius: 14,
    paddingVertical: 8,
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  speedModalTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  speedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  speedRowActive: {
    backgroundColor: 'rgba(255,45,85,0.12)',
  },
  speedRowText: {
    color: '#ddd',
    fontSize: 16,
  },
  speedRowTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  qualityRowTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  qualityRowDescription: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 3,
  },

  ottChromeRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
    justifyContent: 'space-between',
  },
  ottTapZone: {
    position: 'absolute',
    zIndex: 1,
  },
  nonOttTapZone: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
  },
  ottDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    zIndex: 2,
  },
  ottDimPaused: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.25)',
    zIndex: 2,
  },
  ottTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    zIndex: 30,
  },
  speedChipTop: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  qualityChipTop: {
    marginRight: 8,
  },
  volumeControlWrap: {
    position: 'relative',
    marginRight: 8,
  },
  volumeIconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  volumeIconButtonActive: {
    borderColor: shortVideoTheme.crimson,
    backgroundColor: 'rgba(255,45,85,0.18)',
  },
  volumePanel: {
    position: 'absolute',
    top: 42,
    right: 0,
    width: 172,
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(12,12,14,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  volumeMuteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  volumeTrackHit: {
    flex: 1,
    height: 28,
    justifyContent: 'center',
  },
  volumeTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  volumeFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: '#fff',
  },
  volumeThumb: {
    position: 'absolute',
    top: -4,
    width: 12,
    height: 12,
    borderRadius: 6,
    marginLeft: -6,
    backgroundColor: '#fff',
  },
  volumeText: {
    width: 34,
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'right',
  },
  ottCenterWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 25,
  },
  ottSeekRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  ottSeekBtn: {
    minWidth: 58,
    height: 34,
    borderRadius: 8,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.26)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  ottSeekText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  ottPlayPauseFab: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 2,
  },

  bottomMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  bottomMetaTextCol: {
    flex: 1,
    minWidth: 0,
  },
  landscapeToggleBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    marginBottom: 10,
  },

  landscapeChromeRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
  },
  landscapeTapZone: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  landscapeTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 30,
  },
  landscapeTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  landscapeModeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  landscapeModeBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  landscapeCenterWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 25,
  },
  landscapeBottomBar: {
    zIndex: 30,
    width: '100%',
  },
  landscapeTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  landscapeEpText: {
    color: 'rgba(255,255,255,0.75)',
    fontWeight: '600',
  },
});
